### ISSUE TITLE
Offers

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#58]
There is an issue: in the infrastructure we have now, the deliveries and the couriers microservices are responsible for the 'offers' provided in the lecturer Api. Should We change the infrastructure, or, please,  suggest the other ideas?

**Comment by eggwhat** [comment]
Our parcels service is more or less what inquires are. When user provides data for an inquiry such as these
- package:
	width
	length
	height
	weight
- delivery date
- source address
- destination address
- priority (low/high)
- deliveryAtWeekend (true/false)

(in our case its post for parcels service) we should return our calculated price and date for how long our "offer" is valid (in lecturer Api it is **CreateInquireResponse**).  There will be also two "offers" from other companies. I think this part should be covered by service that is now called 'parcels'.

The user chooses an "offer". The post offers is sent to the proper API. Assume user chose us. 
Order service should take care of it. Instead of post offers we use post orders, the user gets 'offerRequestId' and waits until some office worker accepts or rejects this offer. The order eats all the data from inquiry. We can add endpoint for checking if order was accepted yet or not, similar to /offer/request/{offerRequestId}/status. Then this offerRequestId is used as orderId. 

As for deliveries maybe the logic how couriers are assigned should be something like they can see all deliveries for all unassigned orders and just change its status. Maybe there should be an event like OrderApproved -> that creates new delivery.

I would for sure update parcel and orders services to be as close as possible to entities in lecturer API.
